service {
    cluster-name aero80-20260915
    service-threads 48
    proto-fd-max 15000
    proto-fd-idle-ms 0
}
logging {
    console {
        context any info
    }
}
network {
    service {
        address 172.16.0.6
        access-address 172.16.0.6
        port 3000
    }
    heartbeat {
        address 127.0.0.1
        mode mesh
        port 3002
        interval 150
        timeout 10
    }
    fabric {
        address 127.0.0.1
        port 3001
    }
    admin {
        address 127.0.0.1
        port 3003
    }
}
namespace bench80 {
    replication-factor 1
    default-ttl 0
    indexes-memory-budget 8G
    stop-writes-sys-memory-pct 90
    storage-engine device {
        device /dev/md/dragonfly-tiered1
        flush-size 128K
        flush-max-ms 1000
        max-write-cache 1G
        post-write-cache 0
        read-page-cache false
        stop-writes-used-pct 90
        stop-writes-avail-pct 5
    }
}
