# Single-node YCSB device namespace. Performance settings use server defaults.
service {
    cluster-name ycsb-default-20260916
}
logging {
    console {
        context any info
    }
}
network {
    service {
        address 172.16.0.4
        port 3000
    }
    heartbeat {
        address 127.0.0.1
        mode mesh
        port 3002
    }
    fabric {
        address 127.0.0.1
        port 3001
    }
    admin {
        address 127.0.0.1
        port 3003
    }
}
namespace ycsb {
    replication-factor 1
    storage-engine device {
        device /dev/md127p3
    }
}
