#!/usr/bin/env python3
# Copyright (C) 2026 EloqData Inc.
# SPDX-License-Identifier: Apache-2.0

"""Regression checks for release notice retention and dependency selection."""

import importlib.util
import json
from pathlib import Path
import tempfile
import unittest
from unittest.mock import patch


ROOT = Path(__file__).resolve().parent.parent
SPEC = importlib.util.spec_from_file_location("package_notices", ROOT / "scripts/package_notices.py")
notices = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(notices)


class PackageNoticesTest(unittest.TestCase):
    def setUp(self):
        self.temporary = tempfile.TemporaryDirectory()
        self.addCleanup(self.temporary.cleanup)
        self.root = Path(self.temporary.name)
        self.apache = (ROOT / "LICENSE").read_text()
        self.output = notices.Notices(self.apache)

    def write(self, name, text):
        path = self.root / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
        return path

    def test_license_dedup_preserves_custom_attribution_and_terms(self):
        self.output.add("one/LICENSE", self.apache)
        self.output.add("two/LICENSE", self.apache)
        self.output.add("three/LICENSE", self.apache + "\nCopyright Example Authors")
        altered = self.apache.replace("perpetual", "time-limited")
        self.output.add("custom/LICENSE", altered)
        result = self.output.render()
        self.assertIn("one/LICENSE\ntwo/LICENSE", result)
        self.assertIn("Copyright Example Authors", result)
        self.assertIn(altered.strip(), result)
        # Only the deliberately modified terms remain in full.
        self.assertEqual(result.count("TERMS AND CONDITIONS FOR USE"), 1)

    def test_source_notices_at_end_and_quoted_fake_comments(self):
        path = self.write("lua.c", '''const char *s = "/* Copyright fake */";
int example(void) { return 0; }
/* Copyright Lua Authors
 * Permission is hereby granted to retain this complete notice.
 * THE SOFTWARE IS PROVIDED AS IS.
 */
''')
        result = list(notices.source_notices(path))
        self.assertEqual(len(result), 1)
        self.assertIn("THE SOFTWARE IS PROVIDED AS IS.", result[0])
        self.assertNotIn("fake", result[0])

    def test_assembly_notices_are_retained(self):
        path = self.write("crc.asm", "; Copyright Intel\n; Redistribution terms\nsection .text\n")
        self.assertEqual(list(notices.source_notices(path)), ["; Copyright Intel\n; Redistribution terms"])

    def test_empty_source_allowed_but_empty_license_rejected(self):
        path = self.write("empty.h", "")
        self.assertEqual(list(notices.source_notices(path)), [])
        with self.assertRaisesRegex(ValueError, "Empty notice input"):
            self.output.file("dependency/LICENSE", path)

    def test_missing_required_native_notice_fails(self):
        with self.assertRaises(FileNotFoundError):
            notices.native_notices(self.output, self.root, False)

    def test_cmake_cache_comments_and_blank_lines(self):
        path = self.write("CMakeCache.txt", """# Generated by CMake

//Build variant
LAVIK_KERNEL_BYPASS:BOOL=OFF

//Compiler
CMAKE_CXX_COMPILER:FILEPATH=/usr/bin/g++-13

LAVIK_MARCH:STRING=
""")
        self.assertEqual(notices.read_cache(path), {
            "LAVIK_KERNEL_BYPASS": "OFF", "CMAKE_CXX_COMPILER": "/usr/bin/g++-13",
            "LAVIK_MARCH": "",
        })

    def test_go_uses_build_dependencies_and_retains_nested_notices(self):
        self.write("raft/go.mod", "module lavik\ntoolchain go1.26.8\n")
        self.write("go/LICENSE", "Copyright Go Authors\nBSD terms")
        self.write("go/PATENTS", "Go patent grant")
        self.write("go/src/runtime/runtime.go", "// Copyright Go Authors\npackage runtime\n")
        self.write("go/src/cmd/unrelated/LICENSE", "UNUSED COMPILER TOOL")
        self.write("module/LICENSE", self.apache)
        self.write("module/NOTICE", "REQUIRED MODULE ATTRIBUTION")
        self.write("module/internal/copied/NOTICE", "REQUIRED NESTED ATTRIBUTION")
        self.write("module/internal/copied/code.go", "package copied\n")
        self.write("module/unused/LICENSE", "UNUSED PACKAGE")
        module = {"Path": "example.org/dependency", "Version": "v1.2.3", "Dir": str(self.root / "module")}
        packages = [
            {"ImportPath": "runtime", "Dir": str(self.root / "go/src/runtime"), "GoFiles": ["runtime.go"]},
            {"ImportPath": "example.org/dependency/internal/copied", "Module": module,
             "Dir": str(self.root / "module/internal/copied"), "GoFiles": ["code.go"]},
            {"ImportPath": "lavik", "Module": {"Main": True}},
        ]
        with patch.object(notices, "run", side_effect=[str(self.root / "go"),
                          "\n".join(json.dumps(p) for p in packages)]) as run:
            notices.go_notices(self.output, self.root, "go", "cc")
        self.assertEqual(run.call_args.kwargs["env"]["GOTOOLCHAIN"], "go1.26.8")
        self.assertEqual(run.call_args.args[1:], ("list", "-mod=readonly", "-deps", "-json", "./bridge"))
        result = self.output.render()
        for text in ("Go patent grant", "REQUIRED MODULE ATTRIBUTION", "REQUIRED NESTED ATTRIBUTION"):
            self.assertIn(text, result)
        self.assertNotIn("UNUSED", result)
        self.assertIn("example.org/dependency@v1.2.3", result)
        (self.root / "module/LICENSE").unlink()
        with patch.object(notices, "run", side_effect=[str(self.root / "go"),
                          "\n".join(json.dumps(p) for p in packages)]):
            with self.assertRaisesRegex(ValueError, "No license for Go module"):
                notices.go_notices(notices.Notices(self.apache), self.root, "go", "cc")


if __name__ == "__main__":
    unittest.main()
